/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./components/DynamicComponent/A.vue')['default']
    B: typeof import('./components/DynamicComponent/B.vue')['default']
    C: typeof import('./components/DynamicComponent/C.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    CommentDialog: typeof import('./components/SyncSkeleton/CommentDialog.vue')['default']
    LifeComponent: typeof import('./components/LifeComponent.vue')['default']
    MyTeleport: typeof import('./components/TeleportComponent/myTeleport.vue')['default']
    ProvideA: typeof import('./components/ProvideInjectComponents/ProvideA.vue')['default']
    ProvideB: typeof import('./components/ProvideInjectComponents/ProvideB.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./components/SyncSkeleton/Skeleton.vue')['default']
    Tree: typeof import('./components/Tree.vue')['default']
    VmodelVue: typeof import('./components/VmodelVue/VmodelVue.vue')['default']
    WaterFall: typeof import('./components/WaterFall.vue')['default']
  }
}
